language: scala
dist: trusty
os:
  - linux
scala:
  - 2.12.10
jdk:
  - oraclejdk8
cache:
  directories:
  - $HOME/.sbt/0.13/dependency
  - $HOME/.sbt/boot/scala*
  - $HOME/.sbt/launchers
  - $HOME/.ivy2/cache
  - $HOME/.coursier/
script:
  - bin/scalafmt --test
  - sbt "data/run elastic"
  - sbt test
  - sbt server/universal:packageBin

before_script:
  - pushd ..
  - git clone git://github.com/scalacenter/scaladex-small-index.git
  - git clone git://github.com/scalacenter/scaladex-contrib.git
  - popd
