name: CI
on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main 
      - develop
jobs:
  checks:
    name: Scalafmt and Scalafix
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: coursier/setup-action@v1
      - run: sbtn "scalafixAll --check"
      - run: ./bin/scalafmt --test
  unit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Scaladex
        uses: actions/checkout@v2
        with:
          path: scaladex
      - name: Checkout Scaladex small index
        uses: actions/checkout@v2
        with:
          repository: scalacenter/scaladex-small-index
          path: scaladex-small-index
      - name: Checkout Scaladex contrib 
        uses: actions/checkout@v2
        with:
          repository: scalacenter/scaladex-contrib
          path: scaladex-contrib
      - uses: coursier/setup-action@v1
        with:
          jvm: "adopt:1.8"
      - uses: coursier/cache-action@v5
      - name: Unit tests
        env:
          TOKEN_FOR_GITHUB: ${{ secrets.TOKEN }}
        run: |
          cd scaladex
          sbtn test
        shell: bash
      - name: Package server
        run: |
          cd scaladex
          sbtn server/universal:packageBin
        shell: bash
  integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Scaladex
        uses: actions/checkout@v2
        with:
          path: scaladex
      - name: Checkout Scaladex small index
        uses: actions/checkout@v2
        with:
          repository: scalacenter/scaladex-small-index
          path: scaladex-small-index
      - name: Checkout Scaladex contrib
        uses: actions/checkout@v2
        with:
          repository: scalacenter/scaladex-contrib
          path: scaladex-contrib
      - uses: coursier/setup-action@v1
        with:
          jvm: "adopt:1.8"
      - uses: coursier/cache-action@v5
      - name: Integration tests
        env:
          TOKEN_FOR_GITHUB: ${{ secrets.TOKEN }}
        run: |
          cd scaladex
          sbtn 'IntegrationTest / test'
