name: Dependency Graph
on:
  push:
    branches:
      - main
jobs:
  submit:
    name: Submit
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v3
      - uses: scalacenter/sbt-dependency-graph-action@v0.1.0-M1
