name: Dependency Graph
on:
  push:
    branches:
      - main
jobs:
  submit:
    name: Submit Dependency Graph
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: scalacenter/sbt-dependency-graph-action@v1
